### ISSUE TITLE
KeyError occurs set "dn" at attribute_name

### ISSUE THREAD

**Issue by mkouhei** [devpi/devpi-ldap#5]
I tried setting "dn" at attribute_name of user_search, but KeyError occurs.
Would you fix this issue?

I've set this value by reference to the following unit test; user_search_config(), userdn_search_config(), group_user_search_config(), group_userdn_search_config() in tests/test_ldap.py.

```yaml
---
devpi-ldap:
  url: ldap://localhost
  user_search:
    base: dc=example,dc=org
    filter: (&(objectClass=posixAccount)(uid={username}))
    attribute_name: dn
    userdn: cn=admin,dc=example,dc=org
    password: password
  group_search:
    base: dc=example,dc=org
    filter: (&(objectClass=posixAccount)(uid={username}))
    attribute_name: description
```

The same issue occurs in the case also without userdn and password.
```yaml
---
devpi-ldap:
  url: ldap://localhost
  user_search:
    base: dc=example,dc=org
    filter: (&(objectClass=posixAccount)(uid={username}))
    attribute_name: dn
  group_search:
    base: dc=example,dc=org
    filter: (&(objectClass=posixAccount)(uid={username}))
    attribute_name: description
```

Traceback is follows.
```python
2014-10-14 14:51:53,917 ERROR Exception when serving /+login                                                 [39/1918]
Traceback (most recent call last):
  File "/path/to/venv/lib/python3.4/site-packages/waitress/channel.py", line 337, in service
    task.service()
  File "/path/to/venv/lib/python3.4/site-packages/waitress/task.py", line 173, in service
    self.execute()
  File "/path/to/venv/lib/python3.4/site-packages/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/path/to/venv/lib/python3.4/site-packages/devpi_server/views.py", line 118, in __call__
    return self.app(environ, start_response)
  File "/path/to/venv/lib/python3.4/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/path/to/venv/lib/python3.4/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/path/to/venv/lib/python3.4/site-packages/devpi_server/views.py", line 142, in request_log_handler
    response = handler(request)
  File "/path/to/venv/lib/python3.4/site-packages/devpi_server/views.py", line 177, in request_tx_handler
    response = handler(request)
  File "/path/to/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/path/to/venv/lib/python3.4/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/path/to/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/path/to/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/path/to/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/path/to/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 477, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/path/to/venv/lib/python3.4/site-packages/devpi_server/views.py", line 827, in login
    proxyauth = self.auth.new_proxy_auth(user, password)
  File "/path/to/venv/lib/python3.4/site-packages/devpi_server/auth.py", line 83, in new_proxy_auth
    result = self._validate(username, password)
  File "/path/to/venv/lib/python3.4/site-packages/devpi_server/auth.py", line 45, in _validate
    x for x in self.hook(userinfo, authuser, authpassword)
  File "/path/to/venv/lib/python3.4/site-packages/devpi_server/config.py", line 269, in devpiserver_auth_user
    username=username, password=password)
  File "/path/to/venv/lib/python3.4/site-packages/devpi_server/config.py", line 222, in _call_plugins
    results.append(meth(**kwargs))
  File "/path/to/venv/lib/python3.4/site-packages/devpi_ldap/main.py", line 227, in devpiserver_auth_user
    return ldap.validate(username, password)
  File "/path/to/venv/lib/python3.4/site-packages/devpi_ldap/main.py", line 194, in validate
    userdn = self._userdn(username)
  File "/path/to/venv/lib/python3.4/site-packages/devpi_ldap/main.py", line 177, in _userdn
    result = self._search(None, self['user_search'], username=username)
  File "/path/to/venv/lib/python3.4/site-packages/devpi_ldap/main.py", line 153, in _search
    return sum((x['attributes'][attribute_name] for x in conn.response), [])
  File "/path/to/venv/lib/python3.4/site-packages/devpi_ldap/main.py", line 153, in <genexpr>
    return sum((x['attributes'][attribute_name] for x in conn.response), [])
  File "/path/to/venv/lib/python3.4/site-packages/ldap3/utils/caseInsensitiveDictionary.py", line 58, in 
__getitem__
    return self._store[self._getkey(key)]
KeyError: 'dn'
```

I patched follows,

```diff
diff --git a/devpi_ldap/main.py b/devpi_ldap/main.py
index 02dbd02..4c3ad39 100644
--- a/devpi_ldap/main.py
+++ b/devpi_ldap/main.py
@@ -150,7 +150,10 @@ class LDAP(dict):
             config['base'], search_filter,
             search_scope=search_scope, attributes=[attribute_name])
         if found:
-            return sum((x['attributes'][attribute_name] for x in conn.response), [])
+            if attribute_name == 'dn':
+                return sum(([x['dn']] for x in conn.response), [])
+            else:
+                return sum((x['attributes'][attribute_name] for x in conn.response), [])
         else:
             threadlog.error("Search failed %s %s: %s" % (search_filter, config, conn.result))
             return []
```

Best regards,

**Comment by fschulze** [comment]
Fixed with 1.1.1.
